export default {
    name:'banner',
    title:'Banner',
    type:'document',
    fields:[
        {
            name:'image',
            title:'Image',
            type:'array',
            of:[{type:'image'}],
            option:{hotspot:true}
        },
        {
            name:'buttontext',
            title:'ButtonText',
            type:'string',
        },
        {
            name:'product',
            title:'Product',
            type:'string',
        },
        {
            name:'desc',
            title:'Desc',
            type:'string'
        },
        {
            name:'smalltext',
            title:'SmallText',
            type:'string'
        },
        {
            name:'midtext',
            title:'MidText',
            type:'string'
        },
        {
            name:'largertext1',
            title:'LargerText1',
            type:'string'
        },
        {
            name:'largertext2',
            title:'LargerText2',
            type:'string'
        },
        {
            name:'discount',
            title:'Discount',
            type:'string'
        },
        {
            name:'saletime',
            title:'SaleTime',
            type:'string'
        },
    ]
}